spring.application.name=Philharmonic
spring.datasource.url=jdbc:postgresql://localhost:5432/philharmonic
spring.datasource.username=your_user
spring.datasource.password=your_password
spring.jpa.hibernate.ddl-auto=none
#spring.jpa.database-platform=org.hibernate.dialect.PostgresDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

logging.level.root=warn
logging.level.org.springframework.web=debug
logging.level.org.hibernate=debug
